// Service de gestion des données
export const dataService = {
  getData: () => {
    return {
      // Principales offres de BearingPoint
      bpOffers: {
        "BE Capital": ["Capital M&A", "PMI & Carve out"],
        "Customer & Growth": [
          "Digital Strategy & Innovation",
          "Customer Experience",
          "Marketing Transformation",
          "Sales Transformation & Pricing",
          "eCommerce",
          "Data & CRM",
        ],
        "Finance & Risk": [
          "Finance Excellence",
          "Future ERP",
          "Performance Management",
          "Risk Management",
          "Compliance",
          "CFO 4.0 Strategy",
        ],
        Operations: [
          "Product Lifecycle Management",
          "Manufacturing & Maintenance",
          "Logistics Execution",
          "Digital Twin Supply Chain",
          "Demand Management & Planning",
          "Sourcing & Procurement",
        ],
        "People & Strategy": [
          "Talent Management & HR",
          "Change Management",
          "Real Estate & New Ways of Working",
          "Business Strategy",
          "Operational & Process Excellence",
          "Program & Project Mgt",
        ],
        Technology: [
          "Cloud & Sourcing",
          "CIO Advisory",
          "Business Applications",
          "Data, Analytics and AI",
          "Data Security & Privacy",
        ],
      },

      // Structure complète des offres par ligne de service
      completeServiceLines: {
        "Customer & Growth": [
          "Digital Strategy & Innovation",
          "Customer Experience",
          "Marketing Transformation",
          "Sales Transformation & Pricing",
          "eCommerce",
          "Data & CRM",
        ],
        "Finance & Risk": [
          "Finance Excellence",
          "Future ERP",
          "Performance Management",
          "Risk Management",
          "Compliance",
          "CFO 4.0 Strategy",
        ],
        Operations: [
          "Product Lifecycle Management",
          "Manufacturing & Maintenance",
          "Logistics Execution",
          "Digital Twin Supply Chain",
          "Demand Management & Planning",
          "Sourcing & Procurement",
        ],
        "People & Strategy": [
          "Talent Management & HR",
          "Change Management",
          "Real Estate & New Ways of Working",
          "Business Strategy",
          "Operational & Process Excellence",
          "Program & Project Mgt",
        ],
        Technology: [
          "Cloud & Sourcing",
          "CIO Advisory",
          "Business Applications",
          "Data, Analytics and AI",
          "Data Security & Privacy",
        ],
        "BE Capital": ["Capital M&A", "PMI & Carve out"],
      },

      // Actualités de Schneider Electric
      schneiderNews: [
        {
          date: "06 Avr. 2025",
          title: "Fins de carrière à la carte chez Schneider Electric",
          category: "RH, Social",
          description:
            "Accord sur le compte épargne temps permettant aux salariés à trois ans de la retraite de travailler moins.",
        },
        {
          date: "25 Mars 2025",
          title:
            "Schneider Electric débloque 700M$ pour le développement de l'IA aux USA",
          category: "Investissement, Technologie, IA",
          description:
            "Modernisation de sites existants pour répondre à la croissance de l'IA et la demande énergétique.",
        },
        {
          date: "25 Févr. 2025",
          title:
            "Malmené en bourse, Schneider Electric rassurant pour les centres de données",
          category: "Finance, Data Centers",
          description:
            "Chute en bourse suite à des rumeurs d'annulation de contrats avec Microsoft.",
        },
        {
          date: "20 Févr. 2025",
          title:
            "Bénéfice record pour Schneider Electric, tiré par l'efficacité énergétique",
          category: "Finance, Efficacité énergétique",
          description:
            "Forte demande pour les produits liés à l'efficacité énergétique, notamment dans le segment des datacenters.",
        },
        {
          date: "11 Janv. 2025",
          title:
            "Olivier Blum est le nouveau directeur général de Schneider Electric",
          category: "Direction, Gouvernance",
          description:
            "Remplacement de Peter Herweck pour cause de désaccords.",
        },
        {
          date: "04 Déc. 2024",
          title:
            "Schneider Electric et Nvidia développent de nouveaux systèmes de refroidissement",
          category: "Partenariat, Data Centers, IA",
          description:
            "Collaboration pour des systèmes de refroidissement pour centres de données d'IA générative.",
        },
        {
          date: "05 Nov. 2024",
          title: "Schneider Electric victime d'une nouvelle fuite de données",
          category: "Cybersécurité, Sécurité",
          description:
            "Plateforme de développement piratée, attaque par ransomware ayant entraîné le vol de données.",
        },
        {
          date: "30 Oct. 2024",
          title:
            "470M€ d'amendes pour des ententes dans la distribution de matériel électrique",
          category: "Juridique, Conformité",
          description:
            "Amende avec Legrand, Rexel et Sonepar pour ententes sur les prix.",
        },
        {
          date: "17 Oct. 2024",
          title: "Schneider Electric acquiert Motivair pour 850M$",
          category: "Acquisition, Data Centers",
          description:
            "Renforcement sur le segment du refroidissement par fluides dans les data centers.",
        },
        {
          date: "17 Sept. 2024",
          title:
            "Schneider Electric entre dans l'économie circulaire des appareils électriques",
          category: "Développement durable, Économie circulaire",
          description:
            "Réparation et maintenance d'équipements électriques dans des usines à Grenoble.",
        },
      ],

      // Matrice de pertinence précalculée
      relevanceMatrix: [
        {
          news: "Malmené en bourse, Schneider Electric rassurant pour les centres de données",
          newsDate: "25 Févr. 2025",
          newsCategory: "Finance, Data Centers",
          offerCategory: "Finance & Risk",
          relevanceScore: 3,
          offerDetail: "Performance Management, Risk Management",
        },
        {
          news: "Schneider Electric victime d'une nouvelle fuite de données",
          newsDate: "05 Nov. 2024",
          newsCategory: "Cybersécurité, Sécurité",
          offerCategory: "Technology",
          relevanceScore: 3,
          offerDetail: "Data Security & Privacy",
        },
        {
          news: "470M€ d'amendes pour des ententes dans la distribution de matériel électrique",
          newsDate: "30 Oct. 2024",
          newsCategory: "Juridique, Conformité",
          offerCategory: "Finance & Risk",
          relevanceScore: 3,
          offerDetail: "Compliance",
        },
        {
          news: "Schneider Electric acquiert Motivair pour 850M$",
          newsDate: "17 Oct. 2024",
          newsCategory: "Acquisition, Data Centers",
          offerCategory: "BE Capital",
          relevanceScore: 3,
          offerDetail: "Capital M&A, PMI & Carve out",
        },
        {
          news: "Fins de carrière à la carte chez Schneider Electric",
          newsDate: "06 Avr. 2025",
          newsCategory: "RH, Social",
          offerCategory: "People & Strategy",
          relevanceScore: 2,
          offerDetail: "Talent Management & HR",
        },
        {
          news: "Schneider Electric débloque 700M$ pour le développement de l'IA aux USA",
          newsDate: "25 Mars 2025",
          newsCategory: "Investissement, Technologie, IA",
          offerCategory: "Technology",
          relevanceScore: 2,
          offerDetail: "Data, Analytics and AI",
        },
        {
          news: "Bénéfice record pour Schneider Electric, tiré par l'efficacité énergétique",
          newsDate: "20 Févr. 2025",
          newsCategory: "Finance, Efficacité énergétique",
          offerCategory: "Finance & Risk",
          relevanceScore: 2,
          offerDetail: "Finance Excellence, Performance Management",
        },
        {
          news: "Olivier Blum est le nouveau directeur général de Schneider Electric",
          newsDate: "11 Janv. 2025",
          newsCategory: "Direction, Gouvernance",
          offerCategory: "People & Strategy",
          relevanceScore: 2,
          offerDetail: "Change Management",
        },
        {
          news: "Schneider Electric et Nvidia développent de nouveaux systèmes de refroidissement",
          newsDate: "04 Déc. 2024",
          newsCategory: "Partenariat, Data Centers, IA",
          offerCategory: "Technology",
          relevanceScore: 2,
          offerDetail: "Data, Analytics and AI",
        },
        {
          news: "Schneider Electric entre dans l'économie circulaire des appareils électriques",
          newsDate: "17 Sept. 2024",
          newsCategory: "Développement durable, Économie circulaire",
          offerCategory: "Operations",
          relevanceScore: 2,
          offerDetail: "Manufacturing & Maintenance",
        },
        {
          news: "Schneider Electric entre dans l'économie circulaire des appareils électriques",
          newsDate: "17 Sept. 2024",
          newsCategory: "Développement durable, Économie circulaire",
          offerCategory: "People & Strategy",
          relevanceScore: 1,
          offerDetail: "Business Strategy",
        },
      ],

      // Opportunités
      rawOpportunities: [
        {
          id: "173406",
          name: "PQL framework",
          status: "14 - Booked",
          closeDate: "24/10/2024",
          estimatedValue: 30000,
          grossRevenue: 30000,
          serviceLine: "People & Strategy",
          accountManager: "Francois Rovere",
          cm1: "62,78",
          comment:
            "Analyser le système actuel de gestion qualité des projets et proposer une nouvelle mouture sur la base de benchmarks",
          serviceOffering: "Operational & Process Excellence",
        },
        {
          id: "163646",
          name: "Data Excellence Enablement SellOn Dec. 2023",
          status: "14 - Booked",
          closeDate: "21/02/2024",
          estimatedValue: 11000,
          grossRevenue: 11000,
          serviceLine: "Technology",
          accountManager: "Marsida Lekaj",
          cm1: "69,76",
          comment: "Data Excellence support for 2023",
          serviceOffering: "Data, Analytics and AI",
        },
        {
          id: "163656",
          name: "Data Excellence Enablement 2024",
          status: "15 - Lost",
          closeDate: "01/01/2024",
          estimatedValue: 130000,
          grossRevenue: 150000,
          serviceLine: "Technology",
          accountManager: "Marsida Lekaj",
          cm1: "",
          comment: "Data Excellence support for 2023",
          serviceOffering: "Data, Analytics and AI",
        },
        {
          id: "152390",
          name: "Data Excellence Enablement 2023",
          status: "14 - Booked",
          closeDate: "07/02/2023",
          estimatedValue: 180560,
          grossRevenue: 261360,
          serviceLine: "Technology",
          accountManager: "Saskia Vercruyssen",
          cm1: "75,7",
          comment: "Data Excellence support for 2023",
          serviceOffering: "Data, Analytics and AI",
        },
        {
          id: "152607",
          name: "Green Premium Reboot",
          status: "15 - Lost",
          closeDate: "06/01/2023",
          estimatedValue: 108800,
          grossRevenue: 128000,
          serviceLine: "People & Strategy",
          accountManager: "Florent Duval",
          cm1: "",
          comment: "Reboot of green premium sustainable offer",
          serviceOffering: "Business Strategy",
        },
        {
          id: "152341",
          name: "Configurator study - extension Phase 2",
          status: "14 - Booked",
          closeDate: "25/11/2022",
          estimatedValue: 57740,
          grossRevenue: 57740,
          serviceLine: "Customer & Growth",
          accountManager: "Catherine Bouev",
          cm1: "63,94",
          comment: "sellon on the configurator study",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "151732",
          name: "Typology Governance Study",
          status: "15 - Lost",
          closeDate: "16/11/2022",
          estimatedValue: 190000,
          grossRevenue: 190000,
          serviceLine: "Customer & Growth",
          accountManager: "Guillaume Billoir",
          cm1: "",
          comment: "RFP to launch study on data governance typology",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "151274",
          name: "Data Excellence Enablement - 2022 Sell on 2",
          status: "14 - Booked",
          closeDate: "22/11/2022",
          estimatedValue: 56750,
          grossRevenue: 77000,
          serviceLine: "Technology",
          accountManager: "Saskia Vercruyssen",
          cm1: "71,22",
          comment:
            "A deliverable based team associated to the completion of the Data Excellende for 2022",
          serviceOffering: "Data, Analytics and AI",
        },
        {
          id: "151074",
          name: "Configurators study extension",
          status: "14 - Booked",
          closeDate: "31/10/2022",
          estimatedValue: 57320,
          grossRevenue: 57320,
          serviceLine: "Customer & Growth",
          accountManager: "Catherine Bouev",
          cm1: "63,19",
          comment: "Configurators study extension",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "149544",
          name: "Customer Workspace MVP extension",
          status: "14 - Booked",
          closeDate: "14/09/2022",
          estimatedValue: 17204,
          grossRevenue: 17204,
          serviceLine: "Customer & Growth",
          accountManager: "Catherine Bouev",
          cm1: "63,99",
          comment: "Customer Workspace",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "146065",
          name: "Configurators study",
          status: "14 - Booked",
          closeDate: "27/04/2022",
          estimatedValue: 263000,
          grossRevenue: 263000,
          serviceLine: "Customer & Growth",
          accountManager: "Catherine Bouev",
          cm1: "63,19",
          comment: "Configurators study",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "145653",
          name: "Data Excellence Enablement - 2022 Sell on",
          status: "14 - Booked",
          closeDate: "30/04/2022",
          estimatedValue: 165625,
          grossRevenue: 221575,
          serviceLine: "Technology",
          accountManager: "Manu Timmermans",
          cm1: "67,86",
          comment:
            "A deliverable-based surge team associated to the completion of the Data Excellence for the 2022 priority Franchisees.",
          serviceOffering: "Data, Analytics and AI",
        },
        {
          id: "137552",
          name: "Data Excellence Enablement",
          status: "14 - Booked",
          closeDate: "30/04/2021",
          estimatedValue: 109550,
          grossRevenue: 190000,
          serviceLine: "Technology",
          accountManager: "Laurent Fayet",
          cm1: "68,99",
          comment:
            "A deliverable-based surge team associated to the completion of the Data Excellence for the 2021 priority Franchisees.",
          serviceOffering: "Data, Analytics and AI",
        },
        {
          id: "134404",
          name: "Sales Life simplification assistance",
          status: "14 - Booked",
          closeDate: "31/12/2020",
          estimatedValue: 177650,
          grossRevenue: 177650,
          serviceLine: "Customer & Growth",
          accountManager: "Olivier Faulque",
          cm1: "61,21",
          comment: "",
          serviceOffering: "Digital Strategy & Innovation",
        },
        {
          id: "125131",
          name: "ORLM-phase 7( 2020)",
          status: "14 - Booked",
          closeDate: "31/12/2019",
          estimatedValue: 619520,
          grossRevenue: 625000,
          serviceLine: "People & Strategy",
          accountManager: "Guillaume Billoir",
          cm1: "63,01",
          comment:
            "Suite mission de Guillaume Billoir avec Francois Martin Festa",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "122721",
          name: "ORLM- phase 6 - Digital lock",
          status: "14 - Booked",
          closeDate: "30/09/2019",
          estimatedValue: 252110,
          grossRevenue: 253500,
          serviceLine: "People & Strategy",
          accountManager: "Guillaume Billoir",
          cm1: "59,29",
          comment:
            "Suite du job ORLM à partir du 8 juillet jusqu'au 20 dec 2019 avec Guillaume Billoir",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "122334",
          name: "DDG Event Platform Implementation Support",
          status: "15 - Lost",
          closeDate: "22/01/2019",
          estimatedValue: 66000,
          grossRevenue: 66000,
          serviceLine: "People & Strategy",
          accountManager: "Marjolein Biermans",
          cm1: "",
          comment: "Implémentation d'une plateforme d'événements marketing",
          serviceOffering: "Marketing Transformation",
        },
        {
          id: "121975",
          name: "eCommerce RFI support",
          status: "14 - Booked",
          closeDate: "25/10/2019",
          estimatedValue: 63504,
          grossRevenue: 63504,
          serviceLine: "People & Strategy",
          accountManager: "Marjolein Biermans",
          cm1: "63,1",
          comment: "",
          serviceOffering: "Customer Experience",
        },
        {
          id: "121334",
          name: "ORLM Phase 5",
          status: "14 - Booked",
          closeDate: "30/06/2019",
          estimatedValue: 80740,
          grossRevenue: 81400,
          serviceLine: "People & Strategy",
          accountManager: "Guillaume Billoir",
          cm1: "60,40",
          comment: "",
          serviceOffering: "Sales Transformation & Pricing",
        },
        {
          id: "119945",
          name: "Sell-on 9 : Solar – extension Q1/19",
          status: "14 - Booked",
          closeDate: "30/04/2019",
          estimatedValue: 85031,
          grossRevenue: 85031,
          serviceLine: "Finance & Risk",
          accountManager: "Valerie Guichard-Douche",
          cm1: "64,00",
          comment: "",
          serviceOffering: "CFO 4.0 Strategy",
        },
        {
          id: "118222",
          name: "Experience Client Digitale",
          status: "15 - Lost",
          closeDate: "13/03/2019",
          estimatedValue: 100000,
          grossRevenue: 100000,
          serviceLine: "People & Strategy",
          accountManager: "Patrice Begoc",
          cm1: "",
          comment: "",
          serviceOffering: "Customer Experience",
        },
        {
          id: "118152",
          name: "Sell-on 8 : Solar – extension Q1/19",
          status: "14 - Booked",
          closeDate: "28/02/2019",
          estimatedValue: 303416,
          grossRevenue: 432373,
          serviceLine: "Finance & Risk",
          accountManager: "Valerie Guichard-Douche",
          cm1: "64,40",
          comment: "",
          serviceOffering: "CFO 4.0 Strategy",
        },
        {
          id: "116271",
          name: "MA Offer launch customer journey mapping",
          status: "15 - Lost",
          closeDate: "01/02/2018",
          estimatedValue: 50000,
          grossRevenue: 50000,
          serviceLine: "People & Strategy",
          accountManager: "Marjolein Biermans",
          cm1: "",
          comment: "Cartographie du parcours client pour lancement d'offre MA",
          serviceOffering: "Marketing Transformation",
        },
        {
          id: "116035",
          name: "Active Manager for Contact Centers",
          status: "15 - Lost",
          closeDate: "05/09/2019",
          estimatedValue: 150000,
          grossRevenue: 150000,
          serviceLine: "People & Strategy",
          accountManager: "Patrice Begoc",
          cm1: "",
          comment: "",
          serviceOffering: "Service Transformation",
        },
        {
          id: "115859",
          name: "SE DCX-GDPR readiness support",
          status: "15 - Lost",
          closeDate: "04/09/2019",
          estimatedValue: 150000,
          grossRevenue: 150000,
          serviceLine: "Finance & Risk",
          accountManager: "Philippe Mannent",
          cm1: "",
          comment: "",
          serviceOffering: "Compliance",
        },
      ],
    };
  },
};
